// Drop-in FAQ block — renders Claude-authored Q&A pairs for the current URL.
//
// Usage:
//   import { Faq } from "@/app/_components/Faq";
//   <Faq url={`https://www.aiangels.io${pathname}`} />
//
// Data source: faq_content.json (generated by `python generate_faqs.py`).
// Pair with <JsonLdBlock /> — the same FAQ appears in FAQPage schema.

import { promises as fs } from "node:fs";
import path from "node:path";

type Props = { url: string; heading?: string };
type Qa = { q: string; a: string };
type FaqEntry = { slug: string; page_type: string; faqs: Qa[]; generated_at: string };

async function loadFaqs(): Promise<Record<string, FaqEntry>> {
  const full = path.join(process.cwd(), "faq_content.json");
  try {
    const raw = await fs.readFile(full, "utf8");
    return JSON.parse(raw);
  } catch {
    return {};
  }
}

export async function Faq({ url, heading = "Frequently asked questions" }: Props) {
  const map = await loadFaqs();
  const entry = map[url];
  if (!entry || entry.faqs.length === 0) return null;
  return (
    <section aria-label="FAQ" style={{ margin: "3rem 0" }}>
      <h2 style={{ fontSize: "1.5rem", fontWeight: 700, marginBottom: "1rem" }}>{heading}</h2>
      <dl>
        {entry.faqs.map((qa, i) => (
          <div key={i} style={{ marginBottom: "1.25rem" }} data-speakable>
            <dt style={{ fontWeight: 600 }}>{qa.q}</dt>
            <dd style={{ marginInlineStart: 0, marginTop: ".25rem", opacity: 0.9 }}>{qa.a}</dd>
          </div>
        ))}
      </dl>
    </section>
  );
}
